-- Quitamos las foreign keys

CREATE TABLE PRODUCT(PRODUCTID INTEGER NOT NULL PRIMARY KEY,CODE VARCHAR(5),NAME VARCHAR(100),UNITPRICE NUMERIC(6,2) NOT NULL);
CREATE TABLE CUSTOMERID(CUSTOMERID INTEGER NOT NULL PRIMARY KEY,DRV_LIC_NO INTEGER NOT NULL,CONSTRAINT UNI_LIC_NO UNIQUE(DRV_LIC_NO));
CREATE TABLE CUSTOMER(CUSTOMERID INTEGER NOT NULL PRIMARY KEY,NAME VARCHAR(255) NOT NULL);
CREATE TABLE ORDER_DATA(ORDERID INTEGER NOT NULL PRIMARY KEY,ORDERDATE VARCHAR(12),CUSTOMERID INTEGER,AMOUNT NUMERIC(6,2) NOT NULL);
CREATE TABLE LINEITEM(ORDERLINE INTEGER NOT NULL PRIMARY KEY,ORDERID INTEGER NOT NULL,PRODUCTID INTEGER NOT NULL,QUANTITY NUMERIC(4) NOT NULL);
CREATE TABLE CONTACT(CONTACTID VARCHAR(30) NOT NULL PRIMARY KEY,CUSTOMERID INTEGER NOT NULL,ADDRESS VARCHAR(150),CITY VARCHAR(50),PHONE VARCHAR(20));